version: "{build}"
image: Visual Studio 2017
platform:
- Win32

configuration:
- Release

branches:
  only:
    - master

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - cinst 7zip -x86
  - cinst 7zip.commandline -x86
  - 7z x -y "Development.zip" -o"C:\"  

before_build:
  - ps: $Env:PLATFORM_TOOLSET="v141"

build:
  project: agsjoy.sln
  parallel: true
  verbosity: minimal

artifacts:
- path: $(configuration)\agsjoy.dll
  name: agsjoy.dll

deploy: off
