version: "{build}"
image: Visual Studio 2017
platform:
- x86

configuration:
- Release

branches:
  only:
    - master

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - cinst 7zip -x86
  - cinst 7zip.commandline -x86
  - 7z x -y "Development.zip" -o"C:\"  

before_build:
  - ps: $Env:PLATFORM_TOOLSET="v141"

build:
  project: agsjoy.sln
  parallel: true
  verbosity: minimal

artifacts:
- path: $(configuration)\agsjoy.dll
  name: agsjoy.dll

deploy:
- provider: GitHub
  auth_token:
    secure: 0FI9i4tjFfPJYT2ModUijy23Pe3iYp6bizTQR5A4b7uUUwTu7YrniPtcq7JljWG/
  artifact: agsjoy.dll
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
